server:
  port : 8081
  shutdown : graceful

spring:
  graphql:
    path: /graphql
    graphiql:
      path: /graphiql
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 1m
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:mem:graph;DATABASE_TO_UPPER=false
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true